// Code generated by protoc-gen-go. DO NOT EDIT.
// source: demo.proto

package demo

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetRequest struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRequest) Reset()         { *m = GetRequest{} }
func (m *GetRequest) String() string { return proto.CompactTextString(m) }
func (*GetRequest) ProtoMessage()    {}
func (*GetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ca53982754088a9d, []int{0}
}

func (m *GetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRequest.Unmarshal(m, b)
}
func (m *GetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRequest.Marshal(b, m, deterministic)
}
func (m *GetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRequest.Merge(m, src)
}
func (m *GetRequest) XXX_Size() int {
	return xxx_messageInfo_GetRequest.Size(m)
}
func (m *GetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetRequest proto.InternalMessageInfo

func (m *GetRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type GetResponse struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Age                  string   `protobuf:"bytes,2,opt,name=age,proto3" json:"age,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetResponse) Reset()         { *m = GetResponse{} }
func (m *GetResponse) String() string { return proto.CompactTextString(m) }
func (*GetResponse) ProtoMessage()    {}
func (*GetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ca53982754088a9d, []int{1}
}

func (m *GetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetResponse.Unmarshal(m, b)
}
func (m *GetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetResponse.Marshal(b, m, deterministic)
}
func (m *GetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetResponse.Merge(m, src)
}
func (m *GetResponse) XXX_Size() int {
	return xxx_messageInfo_GetResponse.Size(m)
}
func (m *GetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetResponse proto.InternalMessageInfo

func (m *GetResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *GetResponse) GetAge() string {
	if m != nil {
		return m.Age
	}
	return ""
}

type ErrMsg struct {
	BusinessCode         int32    `protobuf:"varint,1,opt,name=business_code,json=businessCode,proto3" json:"business_code,omitempty"`
	BusinessMsg          string   `protobuf:"bytes,2,opt,name=business_msg,json=businessMsg,proto3" json:"business_msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ErrMsg) Reset()         { *m = ErrMsg{} }
func (m *ErrMsg) String() string { return proto.CompactTextString(m) }
func (*ErrMsg) ProtoMessage()    {}
func (*ErrMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_ca53982754088a9d, []int{2}
}

func (m *ErrMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ErrMsg.Unmarshal(m, b)
}
func (m *ErrMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ErrMsg.Marshal(b, m, deterministic)
}
func (m *ErrMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ErrMsg.Merge(m, src)
}
func (m *ErrMsg) XXX_Size() int {
	return xxx_messageInfo_ErrMsg.Size(m)
}
func (m *ErrMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_ErrMsg.DiscardUnknown(m)
}

var xxx_messageInfo_ErrMsg proto.InternalMessageInfo

func (m *ErrMsg) GetBusinessCode() int32 {
	if m != nil {
		return m.BusinessCode
	}
	return 0
}

func (m *ErrMsg) GetBusinessMsg() string {
	if m != nil {
		return m.BusinessMsg
	}
	return ""
}

func init() {
	proto.RegisterType((*GetRequest)(nil), "demo.GetRequest")
	proto.RegisterType((*GetResponse)(nil), "demo.GetResponse")
	proto.RegisterType((*ErrMsg)(nil), "demo.ErrMsg")
}

func init() { proto.RegisterFile("demo.proto", fileDescriptor_ca53982754088a9d) }

var fileDescriptor_ca53982754088a9d = []byte{
	// 245 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x8f, 0xb1, 0x4e, 0xc3, 0x30,
	0x10, 0x86, 0xd5, 0xa4, 0x54, 0xe2, 0x52, 0x50, 0xb9, 0xa9, 0xaa, 0x3a, 0x40, 0x58, 0x98, 0x1a,
	0x95, 0xce, 0xb0, 0x20, 0xd4, 0x29, 0x08, 0x85, 0x07, 0xa8, 0xdc, 0xfa, 0x64, 0x59, 0x22, 0xbe,
	0xe0, 0x73, 0xbb, 0x20, 0x16, 0x5e, 0x81, 0x47, 0xe3, 0x15, 0x78, 0x10, 0x14, 0x87, 0x00, 0xdb,
	0xef, 0xcf, 0xff, 0xdd, 0xfd, 0x3f, 0x80, 0xa6, 0x9a, 0x17, 0x8d, 0xe7, 0xc0, 0x38, 0x6c, 0xf5,
	0x6c, 0x6e, 0x98, 0xcd, 0x33, 0x15, 0xaa, 0xb1, 0x85, 0x72, 0x8e, 0x83, 0x0a, 0x96, 0x9d, 0x74,
	0x9e, 0x7c, 0x0e, 0xb0, 0xa6, 0x50, 0xd1, 0xcb, 0x9e, 0x24, 0xe0, 0x29, 0x24, 0x56, 0x4f, 0x07,
	0xe7, 0x83, 0xab, 0xb4, 0x4a, 0xac, 0xce, 0x57, 0x90, 0xc5, 0x5f, 0x69, 0xd8, 0x09, 0x21, 0xc2,
	0xd0, 0xa9, 0x9a, 0xa2, 0xe1, 0xb8, 0x8a, 0x1a, 0x27, 0x90, 0x2a, 0x43, 0xd3, 0x24, 0xa2, 0x56,
	0xe6, 0x8f, 0x30, 0xba, 0xf7, 0xbe, 0x14, 0x83, 0x97, 0x70, 0xb2, 0xdd, 0x8b, 0x75, 0x24, 0xb2,
	0xd9, 0xb1, 0xee, 0x06, 0x8f, 0xaa, 0x71, 0x0f, 0xef, 0x58, 0x13, 0x5e, 0xc0, 0xef, 0x7b, 0x53,
	0x8b, 0xf9, 0xd9, 0x94, 0xf5, 0xac, 0x14, 0x73, 0x5d, 0x42, 0xf6, 0x44, 0xfe, 0x60, 0x77, 0xf4,
	0xd0, 0x9e, 0xbc, 0x85, 0x74, 0x4d, 0x01, 0x27, 0x8b, 0xd8, 0xf5, 0x2f, 0xfe, 0xec, 0xec, 0x1f,
	0xe9, 0x22, 0xe7, 0xf8, 0xfe, 0xf9, 0xf5, 0x91, 0x8c, 0x11, 0x8a, 0xc3, 0xb2, 0x78, 0xb5, 0xfa,
	0x66, 0xf9, 0xb6, 0x1d, 0xc5, 0xea, 0xab, 0xef, 0x00, 0x00, 0x00, 0xff, 0xff, 0x42, 0x4d, 0xcf,
	0x1a, 0x2c, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ServiceNameClient is the client API for ServiceName service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ServiceNameClient interface {
	//
	// @author xieyt01
	// @reqMetadata *yk_token 运营主体
	// @reqMetadata *orgcode 租户号
	Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error)
}

type serviceNameClient struct {
	cc *grpc.ClientConn
}

func NewServiceNameClient(cc *grpc.ClientConn) ServiceNameClient {
	return &serviceNameClient{cc}
}

func (c *serviceNameClient) Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error) {
	out := new(GetResponse)
	err := c.cc.Invoke(ctx, "/demo.ServiceName/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ServiceNameServer is the server API for ServiceName service.
type ServiceNameServer interface {
	//
	// @author xieyt01
	// @reqMetadata *yk_token 运营主体
	// @reqMetadata *orgcode 租户号
	Get(context.Context, *GetRequest) (*GetResponse, error)
}

// UnimplementedServiceNameServer can be embedded to have forward compatible implementations.
type UnimplementedServiceNameServer struct {
}

func (*UnimplementedServiceNameServer) Get(ctx context.Context, req *GetRequest) (*GetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}

func RegisterServiceNameServer(s *grpc.Server, srv ServiceNameServer) {
	s.RegisterService(&_ServiceName_serviceDesc, srv)
}

func _ServiceName_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceNameServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/demo.ServiceName/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceNameServer).Get(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ServiceName_serviceDesc = grpc.ServiceDesc{
	ServiceName: "demo.ServiceName",
	HandlerType: (*ServiceNameServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _ServiceName_Get_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "demo.proto",
}
